# Generated by Django 4.2.11 on 2024-07-29 19:49

import appfile.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField(choices=[(1, 'Community'), (2, 'Myfiles'), (3, 'Bestpractices')], default=2, verbose_name='id of place file')),
                ('type_id', models.IntegerField(choices=[(1, 'Csv'), (2, 'Json'), (3, 'Pdf')], verbose_name='id type of file')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='date of change')),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='date of delete')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of file')),
                ('link', models.FileField(blank=True, upload_to=appfile.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'json'])], verbose_name='link of file')),
                ('publish', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
        ),
    ]
