# Generated by Django 4.2.11 on 2024-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='b64str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
