# Generated by Django 4.2.11 on 2024-04-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vardapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, verbose_name='name of user')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email of user')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of sign up')),
                ('date_password_change', models.DateTimeField(auto_now=True, verbose_name='date of password change')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='date of change')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name='date of send')),
                ('date_remove', models.DateTimeField(auto_now_add=True, verbose_name='date of remove')),
                ('date_delivery', models.DateTimeField(auto_now_add=True, verbose_name='date of delivery')),
                ('comment', models.TextField(verbose_name='comment')),
                ('chart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vardapp.chart', verbose_name='chart id')),
            ],
        ),
        migrations.CreateModel(
            name='ReadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reading', models.DateTimeField(auto_now_add=True, verbose_name='date of read')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vardapp.comment', verbose_name='id of comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id of user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField(choices=[(1, 'Community'), (2, 'Myfiles'), (3, 'Bestpractices')], default=2, verbose_name='id of place file')),
                ('type_id', models.IntegerField(choices=[(1, 'Csv'), (2, 'Json'), (3, 'Pdf')], verbose_name='id type of file')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='date of change')),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='date of delete')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name of file')),
                ('link', models.FileField(blank=True, upload_to=vardapp.utils.user_directory_path, verbose_name='link of file')),
                ('publish', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('theme', models.CharField(max_length=255, verbose_name='theme of feedback')),
                ('description', models.TextField(verbose_name='feedback')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='date of change')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='dashboard_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vardapp.dashboard', verbose_name='dashboard id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vardapp.file', verbose_name='cells id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type_id', models.IntegerField(choices=[(1, 'Reader'), (2, 'Owner'), (3, 'Commentator'), (4, 'Editor')], verbose_name='access type id')),
                ('date_access_open', models.DateTimeField(auto_now=True, verbose_name='date access open')),
                ('date_access_close', models.DateTimeField(auto_now=True, verbose_name='date access close')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vardapp.file', verbose_name='file id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
    ]
