# Generated by Django 4.2.11 on 2024-03-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vardapp.file', verbose_name='file id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='user id'),
        ),
    ]
