# Generated by Django 4.2.11 on 2024-04-30 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdb',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='chart',
        ),
        migrations.AddField(
            model_name='chart',
            name='clientdata',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='vardapp.clientdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chart',
            name='clientdb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vardapp.clientdb', verbose_name='clientdb id'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='chart',
            field=models.ManyToManyField(blank=True, through='vardapp.ChartDashboard', to='vardapp.chart'),
        ),
    ]
