# Generated by Django 4.2.11 on 2024-03-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0002_alter_access_file_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
