# Generated by Django 4.2.11 on 2024-04-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0002_alter_file_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='file_id',
        ),
        migrations.AddField(
            model_name='access',
            name='owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='owner id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
    ]
