# Generated by Django 4.2.11 on 2024-04-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0003_remove_access_file_id_access_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vardapp.file', verbose_name='file id'),
        ),
    ]
