# Generated by Django 4.2.11 on 2024-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of delete'),
        ),
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(upload_to='', verbose_name='link of file'),
        ),
    ]
