# Generated by Django 4.2.11 on 2024-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0004_alter_file_date_delete_alter_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name of file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type_id',
            field=models.IntegerField(choices=[(1, 'Csv'), (2, 'Json'), (3, 'Pdf')], verbose_name='id type of file'),
        ),
    ]
