# Generated by Django 4.2.11 on 2024-04-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0005_alter_file_name_alter_file_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vardapp.chart', verbose_name='chart id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dashboard_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vardapp.dashboard', verbose_name='dashboard id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vardapp.file', verbose_name='cells id'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name of file'),
        ),
    ]
