# Generated by Django 4.2.11 on 2024-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0006_alter_comment_chart_id_alter_comment_dashboard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(blank=True, upload_to='', verbose_name='link of file'),
        ),
    ]
