# Generated by Django 4.2.11 on 2024-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0007_alter_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name of file'),
        ),
    ]
