# Generated by Django 4.2.11 on 2024-04-01 19:34

from django.db import migrations, models
import vardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vardapp', '0008_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.FileField(blank=True, upload_to=vardapp.models.user_directory_path, verbose_name='link of file'),
        ),
    ]
