# Generated by Django 4.2.11 on 2024-07-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appchart_DB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.AddField(
            model_name='clientdb',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.AddField(
            model_name='chartdashboard',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.chart'),
        ),
        migrations.AddField(
            model_name='chartdashboard',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.dashboard'),
        ),
        migrations.AddField(
            model_name='chart',
            name='clientdata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.clientdata'),
        ),
        migrations.AddField(
            model_name='chart',
            name='clientdb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appchart_DB.clientdb', verbose_name='clientdb id'),
        ),
        migrations.AddField(
            model_name='chart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
    ]
