# Generated by Django 4.2.11 on 2024-08-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='color',
            field=models.CharField(choices=[('#F15C3C', 'Red'), ('#8FC73C', 'Green'), ('#26ADE1', 'Blue'), ('#DE4AF0', 'Purple'), ('#FCD205', 'Yellow'), ('#6C6C6C', 'Grey')], default='#26ADE1', max_length=15, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='chart',
            name='image_format',
            field=models.IntegerField(choices=[(1, 'Png'), (2, 'Ps'), (3, 'Pdf'), (4, 'Svg')], default=0, verbose_name='image format'),
        ),
        migrations.AddField(
            model_name='chart',
            name='plot_type',
            field=models.IntegerField(choices=[(1, 'Plot'), (2, 'Scatter'), (3, 'Bar'), (4, 'Pie'), (5, 'Stackplot')], default=0, verbose_name='plot type'),
        ),
        migrations.AddField(
            model_name='chart',
            name='x_data',
            field=models.CharField(blank=True, default='A', max_length=3, null=True, verbose_name='x data'),
        ),
        migrations.AddField(
            model_name='chart',
            name='x_label',
            field=models.CharField(blank=True, default='X', max_length=3, null=True, verbose_name='x label'),
        ),
        migrations.AddField(
            model_name='chart',
            name='y_data',
            field=models.CharField(blank=True, default='B', max_length=3, null=True, verbose_name='y data'),
        ),
        migrations.AddField(
            model_name='chart',
            name='y_label',
            field=models.CharField(blank=True, default='y', max_length=3, null=True, verbose_name='y label'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='clientdata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.clientdata', verbose_name='clientdata'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='str_query',
            field=models.TextField(blank=True, verbose_name='query'),
        ),
    ]
