# Generated by Django 4.2.11 on 2024-08-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='clientdata',
        ),
        migrations.RemoveField(
            model_name='clientdb',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='clientdb',
            name='str_datas_for_connection',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='charts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.chart', verbose_name='charts id'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='extension',
            field=models.IntegerField(choices=[(1, 'json api'), (3, 'excel xlsx'), (5, 'csv'), (6, 'json')], default=1),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='connection_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='data_base_name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='data_base_type',
            field=models.CharField(choices=[(1, 'MSSQL SQLAlchemy mssql+pyodbc'), (2, 'MYSQL SQLAlchemy mysql+pymysql'), (3, 'MARIADB SQLAlchemy mssql+pyodbc'), (4, 'POSTGRES SQLAlchemy postgresql+psycopg2')]),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='host',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='user_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
