# Generated by Django 4.2.11 on 2024-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0003_chart_color_chart_image_format_chart_plot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
