# Generated by Django 4.2.11 on 2024-08-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0003_remove_chart_clientdata_remove_clientdb_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='extension',
            field=models.IntegerField(choices=[(1, 'json api'), (3, 'excel xlsx'), (5, 'csv'), (6, 'json')]),
        ),
    ]
