# Generated by Django 4.2.11 on 2024-08-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0004_alter_clientdata_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='charts_id',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='extension',
        ),
        migrations.AddField(
            model_name='chart',
            name='clientdata',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.clientdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='extension',
            field=models.IntegerField(choices=[(1, 'json api'), (3, 'excel xlsx'), (5, 'csv'), (6, 'json')], default=1),
        ),
    ]
