# Generated by Django 4.2.11 on 2024-08-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0004_chart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='plot',
            field=models.TextField(blank=True, null=True, verbose_name='plot_in_base64'),
        ),
    ]
