# Generated by Django 4.2.11 on 2024-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0005_chart_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='x_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='x data'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='x_label',
            field=models.CharField(blank=True, default='X', max_length=100, null=True, verbose_name='x label'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='y_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='y data'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='y_label',
            field=models.CharField(blank=True, default='y', max_length=100, null=True, verbose_name='y label'),
        ),
    ]
