# Generated by Django 4.2.11 on 2024-08-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0005_remove_clientdata_charts_id_and_more'),
        ('appchart_DB', '0006_alter_chart_x_data_alter_chart_x_label_and_more'),
    ]

    operations = [
    ]
