# Generated by Django 4.2.11 on 2024-08-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0007_merge_20240813_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='clientdata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.clientdata', verbose_name='clientdata'),
        ),
    ]
