# Generated by Django 4.2.11 on 2024-08-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchart_DB', '0008_dashboard_data_alter_chart_clientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdb',
            name='data_base_type',
            field=models.CharField(choices=[(1, 'MSSQL SQLAlchemy mssql+pyodbc'), (2, 'MYSQL SQLAlchemy mysql+pymysql'), (3, 'MARIADB SQLAlchemy mssql+pyodbc'), (4, 'POSTGRES SQLAlchemy postgresql+psycopg2')], null=True),
        ),
    ]
