# Generated by Django 4.2.11 on 2024-07-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appchart_DB', '0002_initial'),
        ('appcomment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readcomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id of user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='chart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.chart', verbose_name='chart id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dashboard_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appchart_DB.dashboard', verbose_name='dashboard id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfile.file', verbose_name='file id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.AlterUniqueTogether(
            name='readcomment',
            unique_together={('comment_id', 'user_id')},
        ),
    ]
