# Generated by Django 4.2.11 on 2024-08-20 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appinvite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='date_invite',
            new_name='date_invite_open',
        ),
        migrations.AddField(
            model_name='invite',
            name='access_type_id',
            field=models.IntegerField(choices=[(1, 'Reader'), (3, 'Commentator'), (4, 'Editor')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='date_invite_close',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('owner_id', 'email')},
        ),
    ]
