# Generated by Django 4.2.11 on 2024-08-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinvite', '0002_rename_date_invite_invite_date_invite_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='date_invite_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
