# Generated by Django 4.2.11 on 2024-08-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinvite', '0003_alter_invite_date_invite_close'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='date_invite_open',
            new_name='date_invite',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='date_invite_close',
        ),
    ]
