# Generated by Django 4.2.11 on 2024-08-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinvite', '0004_rename_date_invite_open_invite_date_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status_sending',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
