# Generated by Django 4.2.11 on 2024-04-21 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('date_remove', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('user_id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_owner', to=settings.AUTH_USER_MODEL)),
                ('user_id_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
