# Generated by Django 4.2.11 on 2024-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('date_remove', models.DateTimeField(auto_now=True)),
                ('is_remove', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
        ),
    ]
