# Generated by Django 4.2.11 on 2024-04-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_remove',
            field=models.DateTimeField(null=True),
        ),
    ]
