# Generated by Django 4.2.11 on 2024-07-29 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appchat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('date_remove', models.DateTimeField(auto_now=True)),
                ('is_remove', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('doc', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appchat.chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
