# Generated by Django 4.2.11 on 2024-07-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchat', '0003_remove_chat_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='date_remove',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_remove',
        ),
    ]
