# Generated by Django 4.2.11 on 2024-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchat', '0003_alter_chat_date_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_remove',
            field=models.BooleanField(null=True),
        ),
    ]
