# Generated by Django 4.2.11 on 2024-08-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchat', '0004_remove_chat_date_remove_remove_message_date_remove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_remove',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_id',
        ),
    ]
