# Generated by Django 4.2.11 on 2024-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchat', '0004_chat_is_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_remove',
            field=models.BooleanField(default=False),
        ),
    ]
