# Generated by Django 4.2.11 on 2024-03-23 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=128)),
                ('driver', models.IntegerField(choices=[(1, 'SQLAlchemy for MySQL')], default=1)),
                ('url', models.CharField(max_length=255)),
                ('host', models.CharField(default='localhost', max_length=60)),
                ('port', models.IntegerField(default=3306)),
                ('data_base_type', models.CharField(max_length=255)),
                ('data_base_name', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=255)),
                ('str_query', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
