# Generated by Django 4.2.11 on 2024-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquery', '0002_clientdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdb',
            name='data_base_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='host',
            field=models.CharField(default='localhost', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='port',
            field=models.IntegerField(default=3306, null=True),
        ),
        migrations.AlterField(
            model_name='clientdb',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
